// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/lib')['Avatar']
    ABadge: typeof import('ant-design-vue/lib')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/lib')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/lib')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/lib')['Button']
    ACard: typeof import('ant-design-vue/lib')['Card']
    ACardGrid: typeof import('ant-design-vue/lib')['CardGrid']
    ACheckbox: typeof import('ant-design-vue/lib')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/lib')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/lib')['Col']
    AConfigProvider: typeof import('ant-design-vue/lib')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/lib')['Dropdown']
    AForm: typeof import('ant-design-vue/lib')['Form']
    AFormItem: typeof import('ant-design-vue/lib')['FormItem']
    AInput: typeof import('ant-design-vue/lib')['Input']
    AInputPassword: typeof import('ant-design-vue/lib')['InputPassword']
    ALayout: typeof import('ant-design-vue/lib')['Layout']
    ALayoutContent: typeof import('ant-design-vue/lib')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/lib')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/lib')['LayoutSider']
    AList: typeof import('ant-design-vue/lib')['List']
    AListItem: typeof import('ant-design-vue/lib')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/lib')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/lib')['Menu']
    AMenuItem: typeof import('ant-design-vue/lib')['MenuItem']
    APagination: typeof import('ant-design-vue/lib')['Pagination']
    APopconfirm: typeof import('ant-design-vue/lib')['Popconfirm']
    APopover: typeof import('ant-design-vue/lib')['Popover']
    ARadio: typeof import('ant-design-vue/lib')['Radio']
    ARadioGroup: typeof import('ant-design-vue/lib')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/lib')['RangePicker']
    ARow: typeof import('ant-design-vue/lib')['Row']
    ASelect: typeof import('ant-design-vue/lib')['Select']
    ASelectOption: typeof import('ant-design-vue/lib')['SelectOption']
    ASubMenu: typeof import('ant-design-vue/lib')['SubMenu']
    ATable: typeof import('ant-design-vue/lib')['Table']
    ATabPane: typeof import('ant-design-vue/lib')['TabPane']
    ATabs: typeof import('ant-design-vue/lib')['Tabs']
    ATextarea: typeof import('ant-design-vue/lib')['Textarea']
    ATooltip: typeof import('ant-design-vue/lib')['Tooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
